name: "Run CI"

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: pre-commit run --all-files
  tests:
    needs: pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: setup-pixi
        uses: prefix-dev/setup-pixi@v0.5.1
      - run: pixi run test
