name: "Run CI"

on: pull_request

- name: setup-pixi
  uses: prefix-dev/setup-pixi@v0.5.1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pixi run test
