name: "Run CI"

on: pull_request

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-pixi
        uses: prefix-dev/setup-pixi@v0.5.1
      - run: pixi run test

